// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Training.Models;

namespace Training.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20180313023359_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Training.Models.Politics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PoliticalParty");

                    b.HasKey("Id");

                    b.ToTable("Politics");
                });

            modelBuilder.Entity("Training.Models.Pollsters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<int?>("FK_Politics_Pollster");

                    b.Property<int>("PoliticsId");

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("FK_Politics_Pollster");

                    b.ToTable("Pollsters");
                });

            modelBuilder.Entity("Training.Models.Pollsters", b =>
                {
                    b.HasOne("Training.Models.Politics", "Politics")
                        .WithMany()
                        .HasForeignKey("FK_Politics_Pollster");
                });
#pragma warning restore 612, 618
        }
    }
}
